"""Add password reset tokens table

Revision ID: 302cd8b4c5ae
Revises: 
Create Date: 2025-10-12 22:00:19.692635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '302cd8b4c5ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.drop_constraint(op.f('daily_summaries_vehicle_id_date_key'), 'daily_summaries', type_='unique')
    op.drop_constraint(op.f('daily_summaries_vehicle_id_fkey'), 'daily_summaries', type_='foreignkey')
    op.drop_constraint(op.f('daily_summaries_driver_id_fkey'), 'daily_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'daily_summaries', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'daily_summaries', 'vehicles', ['vehicle_id'], ['id'])
    op.alter_column('deficits', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('deficits', 'deficit_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'deficit'::text"))
    op.drop_constraint(op.f('deficits_vehicle_fkey'), 'deficits', type_='foreignkey')
    op.drop_constraint(op.f('deficits_driver_fkey'), 'deficits', type_='foreignkey')
    op.create_foreign_key(None, 'deficits', 'vehicles', ['vehicle'], ['id'])
    op.create_foreign_key(None, 'deficits', 'drivers', ['driver'], ['id'])
    op.alter_column('drivers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drivers', 'license_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drivers', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drivers', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('drivers', 'experience',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('drivers', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('locations', 'driver_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint(op.f('locations_driver_id_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'drivers', ['driver_id'], ['id'])
    op.alter_column('trips', 'collected_amount',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('trips', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('trips_driver_id_fkey'), 'trips', type_='foreignkey')
    op.drop_constraint(op.f('trips_vehicle_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'drivers', ['driver_id'], ['id'])
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('vehicles', 'reg_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('vehicles', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('vehicles', 'owner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'NO_OWNER_RECORDED'::text"))
    op.alter_column('vehicles', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vehicles', 'owner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'NO_OWNER_RECORDED'::text"))
    op.alter_column('vehicles', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vehicles', 'reg_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_vehicle_id_fkey'), 'trips', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('trips_driver_id_fkey'), 'trips', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trips', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trips', 'collected_amount',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_driver_id_fkey'), 'locations', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.alter_column('locations', 'driver_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('drivers', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drivers', 'experience',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('drivers', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('drivers', 'license_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'deficits', type_='foreignkey')
    op.drop_constraint(None, 'deficits', type_='foreignkey')
    op.create_foreign_key(op.f('deficits_driver_fkey'), 'deficits', 'drivers', ['driver'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('deficits_vehicle_fkey'), 'deficits', 'vehicles', ['vehicle'], ['id'], onupdate='CASCADE')
    op.alter_column('deficits', 'deficit_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'deficit'::text"))
    op.alter_column('deficits', 'amount',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'daily_summaries', type_='foreignkey')
    op.drop_constraint(None, 'daily_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('daily_summaries_driver_id_fkey'), 'daily_summaries', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('daily_summaries_vehicle_id_fkey'), 'daily_summaries', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('daily_summaries_vehicle_id_date_key'), 'daily_summaries', ['vehicle_id', 'date'])
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_token', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
