"""Create core tables

Revision ID: initial_migration
Revises:
Create Date: 2025-10-12 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'initial_migration'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create routes table
    op.create_table('routes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, onupdate=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )

    # Create users table
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, onupdate=sa.text('now()')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    # Create vehicles table
    op.create_table('vehicles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('insurance_expiry', sa.Date(), nullable=False),
    sa.Column('tlb_expiry', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, onupdate=sa.text('now()')),
    sa.Column('passenger_capacity', sa.Numeric(), nullable=True),
    sa.Column('inspection_expiry', sa.Date(), nullable=True),
    sa.Column('speed_governor_expiry', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no')
    )
    op.create_index('idx_vehicles_status', 'vehicles', ['status'], unique=False)

    # Create drivers table
    op.create_table('drivers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('license_no', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, onupdate=sa.text('now()')),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_no')
    )
    op.create_index('idx_drivers_status', 'drivers', ['status'], unique=False)

    # Create trips table
    op.create_table('trips',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('driver_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('collected_amount', sa.Integer(), nullable=False),
    sa.Column('repair_expense', sa.Numeric(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, onupdate=sa.text('now()')),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trips_driver_id', 'trips', ['driver_id'], unique=False)
    op.create_index('idx_trips_vehicle_id', 'trips', ['vehicle_id'], unique=False)
    op.create_index('idx_trips_status', 'trips', ['status'], unique=False)

    # Create locations table
    op.create_table('locations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('driver_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_driver_id', 'locations', ['driver_id'], unique=False)

    # Create daily_summaries table
    op.create_table('daily_summaries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('driver_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trip_count', sa.Integer(), nullable=False),
    sa.Column('total_passengers', sa.Integer(), nullable=False),
    sa.Column('total_expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_collected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, onupdate=sa.text('now()')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create deficits table
    op.create_table('deficits',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vehicle', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('deficit_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['driver'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deficits')
    op.drop_table('daily_summaries')
    op.drop_table('locations')
    op.drop_table('trips')
    op.drop_table('drivers')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('routes')
    # ### end Alembic commands ###
